# -*- coding: utf-8 -*-
"""InventoryManagementSystem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l1wkHna1wXTPRuNVlsLBccUUyhZzNOnT
"""

import json
import time

#created a JSON file
# data={1001:{'name':'Table','price':5500,'stock':100},
#       1002:{'name':'Chair','price':3200,'stock':100},
#       1003:{'name':'Lamp','price':1100,'stock':100},
#       1004:{'name':'Cupboard','price':1200,'stock':100},
#       1005:{'name':'pencil','price':12,'stock':100}}
# js=json.dumps(data)
# fd=open("data.json","w")
# fd.write(js)
# fd.close()

# created a JSON file
# sales={'7011060471':{'customer_name':'Aditya','customer_item':1004,'customer_bill':2400},
#        '1236547895':{'customer_name':'Rohan','customer_item':1002,'customer_bill':6400}}
# js=json.dumps(sales)
# fd=open("sales.json","w")
# fd.write(js)
# fd.close()

def menu():
  print("*************************************************")
  print("*************** Welcome to ADG store ************")
  print("*************************************************")
  print("1-->SEE ALL AVAILABLE ITEMS")
  print("2-->BUY ITEM(S)")
  print("3-->CHANGE INVENTORY VALUES(ONLY FOR STAFF)")
  print("4-->SEE SALES")
  print("5-->EXIT")
  choice=int(input("enter your choice(1/2/3)--->"))
  if choice==1:
    data()
  if choice==2:
    main()
  if choice==3:
    print("1-->ADD ITEM(S)")
    print("2-->DELETE ITEM(S)")
    choice=int(input("Enter your choice here--->"))
    if choice==1:
      add()
    if choice==2:
      delete()
    else:
      print("PLEASE ENTER A VALID CHOICE!!!")
      menu()
  if choice==4:
    sale()
  if choice==5:
    exit()
  else:
    print("PLEASE ENTER VALID CHOICE!!!")
    print("")
    print("")
    print("")
    menu()


def data():
  fd = open("data.json",'r')
  r = fd.read()
  fd.close()
  data=json.loads(r)
  print("********************************** INVENTORY DATA ********************************")
  print("**********************************************************************************")
  for i in data:
    print('--->','P_ID:',i,'     ','P_NAME:',data[i]['name'],'     ','P_PRICE:',data[i]['price'],'     ','P_STOCK:',data[i]['stock'])
    print("**********************************************************************************")
  print("")
  print("")
  print("")
  menu()


def main():
  fd = open("data.json",'r')
  r = fd.read()
  fd.close()
  data = json.loads(r)

  name=input(("Please enter your name--->"))
  Pno=int(input("please enter your phone number--->"))
  id=input("enter item ID--->")
  quant=int(input("enter quantity of item(s) to buy--->"))
  print("")
  print("########################################################")
  print("####################### ADG Store ######################")
  print("###############",time.ctime(),"###############")
  print("--------------------------------------------------------")
  print('Name:',name,'               ','Mob:','(',Pno,')')
  print("NAME:",data[id]['name'],"              ","PRICE:
  ",data[id]['price'])
  print("--------------------------------------------------------")
  print("Billing Amt:",(data[id]['price'])*quant,'(incl. of all taxes)')
  print("--------------------------------------------------------")
  print("################# THANK YOU FOR VISITING ###############")
  data[id]['stock']=data[id]['stock']-quant

  fd2 = open("sales.json",'r')
  r2 = fd2.read()
  fd2.close()
  record = json.loads(r2)
  record[str(Pno)]={'customer_name':name,'customer_item':data[id]['name'],'customer_bill':(data[id]['price'])*quant}
  js1=json.dumps(record)
  fd1=open("sales.json","w")
  fd1.write(js1)
  fd1.close()

  js=json.dumps(data)
  fd=open("data.json","w")
  fd.write(js)
  fd.close()
  print("")
  print("")
  print("")
  menu()


def add():
  for i in range(9999):
    fd = open("data.json",'r')
    r = fd.read()
    fd.close()
    data=json.loads(r)

    p_id=int(input("enter Product ID--->"))
    p_name=input("enter product name--->")
    p_price=int(input("enter product price--->"))
    p_stock=int(input("enter product stock--->"))
    data[p_id]={'name':p_name,'price':p_price,'stock':p_stock}

    js = json.dumps(data)
    fd = open("data.json",'w')
    fd.write(js)
    fd.close()

    choice2=input("do you want to add more?(y/n)--->")
    if choice2=="n":
      break;
  print("")
  print("")
  print("")
  menu()


def delete():
  for i in range(9999):
    fd = open("data.json",'r')
    r = fd.read()
    fd.close()
    data=json.loads(r)

    p_id=input("enter Product ID--->")
    del data[p_id]

    js = json.dumps(data)
    fd = open("data.json",'w')
    fd.write(js)
    fd.close()
    choice=input("do you want to delete more?(y/n)--->")
    if choice=='n':
      break;
  print("")
  print("")
  print("")
  menu()


def sale():
  fd = open("sales.json",'r')
  r = fd.read()
  fd.close()
  data=json.loads(r)
  print("********************************** SALES REPORT **********************************")
  print("**********************************************************************************")
  for i in data:
    print('--->','CUSTOMER_MOB:',i,'     ','CUSTOMER_NAME:',data[i]['customer_name'],'     ','CUSTOMER_BILL:',data[i]['customer_bill'])
    print("**********************************************************************************")
  print("")
  print("")
  print("")
  menu()


def exit():
  print("PLEASE VISIT AGAIN :)")


menu()